name: Python CI

on:
  push:
    branches:
      - main

env:
  APP_NAME: ${{ vars.APP_NAME }}
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}

jobs:
  build:

    runs-on: Linux

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Print Variables
        run: |
          echo "App Name: $APP_NAME"
          echo "Environment: $ENVIRONMENT"

      - run: pytest
